function [ tev ] = gentev( t )
% gentev computes eigenvalues of the BCCB matrix in which the BTTB T_{mn}
% is embedded:
% t : the matrix generated by fcolrow.a see A.9 ;
% tev : the output eigenvalues of the BCCB matrix

tev = fft2 (t);
end

