function [ y ] = l1cinvx( ev,d )
%L1CINVX solves the preconditioning system Cy = d with CB preconditioner
% ev: the matrix generated by genl1ev.m, see A. 13;
% d : the right hand side vector; 
% y : the output solution

[n,m] = size (ev);
m = m/2;
rex = reshape (d,n,m);
rex = fft(rex);

for i = 1:n
    A = toeplitz (ev(i,1:m), [ev(i,1), ev(i, 2*m:-1:m+2)]);
    rex(i,:) = (A\((rex(i,:))'))';
end
rex = ifft(rex);
y = reshape (rex, m*n,1);

end

